/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shop.gui;

import com.shop.BeanProvider;
import com.shop.domain.ProductCompany;
import com.shop.services.PurchaseService;
import java.util.ArrayList;
import javax.swing.JFrame;
import java.util.List;
import com.shop.utils.CompanyRenderer;
import org.springframework.beans.factory.annotation.Autowired;

import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;
import com.shop.domain.Product;
import com.shop.utils.ProductRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lulu
 */
public class PurchasePageUI extends javax.swing.JInternalFrame {

    EventList<ProductCompany> itemEventList;
    EventList<Product> prodEventList;
    DefaultTableModel model;

    /**
     * Creates new form PurchasePageUI
     */
    @Autowired
    PurchaseService purchaseService;

    public PurchasePageUI() {
        initComponents();
        BeanProvider.autowire(this);
        try {
            List<ProductCompany> company = purchaseService.getAllCompany();
            if (company != null) {
                itemEventList = GlazedLists.eventList(company);
                AutoCompleteSupport.install(cpmpCombo, itemEventList);

            }

            cpmpCombo.setRenderer(new CompanyRenderer(company));
            cpmpCombo.setSelectedIndex(0);
            ProductCompany company1 = (ProductCompany) cpmpCombo.getSelectedItem();
            List<Product> products = purchaseService.getComboProducts(company1);
            if (products != null) {
                prodEventList = GlazedLists.eventList(products);
                AutoCompleteSupport.install(prodCombo, prodEventList);
            }

            prodCombo.setRenderer(new ProductRenderer(products));
            
        } catch (Exception e) {
            new ExceptionUI(new javax.swing.JFrame(), true, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPain = new javax.swing.JPanel();
        catPan = new javax.swing.JPanel();
        cpmpCombo = new javax.swing.JComboBox<>();
        compLbl = new javax.swing.JLabel();
        prodLbl = new javax.swing.JLabel();
        prodCombo = new javax.swing.JComboBox<>();
        prodAddBtn = new javax.swing.JButton();
        compAddBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        cpmpCombo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cpmpCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cpmpCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cpmpComboItemStateChanged(evt);
            }
        });
        cpmpCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpmpComboMouseClicked(evt);
            }
        });

        compLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compLbl.setText("Company : ");

        prodLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodLbl.setText("Product: ");

        prodCombo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        prodCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodComboMouseClicked(evt);
            }
        });

        prodAddBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        prodAddBtn.setText("+");
        prodAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodAddBtnActionPerformed(evt);
            }
        });

        compAddBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        compAddBtn.setText("+");
        compAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compAddBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Quantity : ");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        addButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catPanLayout = new javax.swing.GroupLayout(catPan);
        catPan.setLayout(catPanLayout);
        catPanLayout.setHorizontalGroup(
            catPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(catPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodLbl)
                    .addComponent(compLbl))
                .addGap(12, 12, 12)
                .addGroup(catPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cpmpCombo, 0, 350, Short.MAX_VALUE)
                    .addComponent(prodCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(catPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catPanLayout.setVerticalGroup(
            catPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catPanLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(catPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpmpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compLbl)
                    .addComponent(compAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(catPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodLbl)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL.No.", "Company Name", "Product Name", "MRP", "Qnt.", "Price", "product"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pTable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL PRICE : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("0.00");

        jButton2.setText("SUBMIT");

        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 600, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPainLayout = new javax.swing.GroupLayout(mainPain);
        mainPain.setLayout(mainPainLayout);
        mainPainLayout.setHorizontalGroup(
            mainPainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPainLayout.setVerticalGroup(
            mainPainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPainLayout.createSequentialGroup()
                .addComponent(catPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compAddBtnActionPerformed
        // TODO add your handling code here:

        COmpanyAddUI compDialog = new COmpanyAddUI(new JFrame(), true);
        compDialog.setLocationRelativeTo(null);
        compDialog.setVisible(true);
    }//GEN-LAST:event_compAddBtnActionPerformed

    private void prodAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodAddBtnActionPerformed
        // TODO add your handling code here:
        try {
            ProductAddUI prodDialog = new ProductAddUI(new JFrame(), true);
            prodDialog.setLocationRelativeTo(null);
            prodDialog.setVisible(true);
            ProductCompany company = (ProductCompany) cpmpCombo.getSelectedItem();
            List<Product> products = purchaseService.getComboProducts(company);
            System.out.println("data--->" + products);
//            prodEventList = GlazedLists.eventList(products);
            prodCombo.setRenderer(new ProductRenderer(products));
        } catch (Exception e) {
            new ExceptionUI(new javax.swing.JFrame(), true, e.toString());
        }
    }//GEN-LAST:event_prodAddBtnActionPerformed

    private void prodComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_prodComboMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cpmpComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpmpComboMouseClicked
        // TODO add your handling code here:
        ProductCompany company = (ProductCompany) cpmpCombo.getSelectedItem();
        System.out.println(company);
    }//GEN-LAST:event_cpmpComboMouseClicked

    private void cpmpComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cpmpComboItemStateChanged
        // TODO add your handling code here:
        setProductCombo();
    }//GEN-LAST:event_cpmpComboItemStateChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        int sl = pTable.getRowCount();
    }//GEN-LAST:event_addButtonActionPerformed

    void setProductCombo() {
        ProductCompany company = (ProductCompany) cpmpCombo.getSelectedItem();
        System.out.println(company);
        try {
            List<Product> products = purchaseService.getComboProducts(company);
            if (products != null) {
                prodCombo.setRenderer(new ProductRenderer(products));
            }

            
        } catch (Exception e) {
            new ExceptionUI(new javax.swing.JFrame(), true, e.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel catPan;
    private javax.swing.JButton compAddBtn;
    private javax.swing.JLabel compLbl;
    private javax.swing.JComboBox<String> cpmpCombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPain;
    private javax.swing.JTable pTable;
    private javax.swing.JButton prodAddBtn;
    private javax.swing.JComboBox<String> prodCombo;
    private javax.swing.JLabel prodLbl;
    // End of variables declaration//GEN-END:variables
}
